<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="12" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="278895" started-at="2021-11-22T14:58:31 IST" finished-at="2021-11-22T15:03:10 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="14851" started-at="2021-11-22T14:58:31 IST" finished-at="2021-11-22T14:58:46 IST">
      <class name="com.comprehensive.testCases.Homepage_TC">
        <test-method status="PASS" signature="Homepage()[pri:0, instance:com.comprehensive.testCases.Homepage_TC@a3d8174]" name="Homepage" duration-ms="10423" started-at="2021-11-22T14:58:31 IST" finished-at="2021-11-22T14:58:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Homepage -->
      </class> <!-- com.comprehensive.testCases.Homepage_TC -->
    </test> <!-- Test -->
    <test name="Test1" duration-ms="26892" started-at="2021-11-22T14:58:46 IST" finished-at="2021-11-22T14:59:12 IST">
      <class name="com.comprehensive.testCases.LoginTest">
        <test-method status="FAIL" signature="Loginpage()[pri:0, instance:com.comprehensive.testCases.LoginTest@793be5ca]" name="Loginpage" duration-ms="22546" started-at="2021-11-22T14:58:46 IST" finished-at="2021-11-22T14:59:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Account– Bigsmall.in] but found [Challenge– Bigsmall.in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Account– Bigsmall.in] but found [Challenge– Bigsmall.in]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.comprehensive.testCases.LoginTest.Loginpage(LoginTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginpage -->
      </class> <!-- com.comprehensive.testCases.LoginTest -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="23735" started-at="2021-11-22T14:59:12 IST" finished-at="2021-11-22T14:59:36 IST">
      <class name="com.comprehensive.testCases.Hoveraction_TC">
        <test-method status="PASS" signature="Hover()[pri:0, instance:com.comprehensive.testCases.Hoveraction_TC@50b5ac82]" name="Hover" duration-ms="19536" started-at="2021-11-22T14:59:12 IST" finished-at="2021-11-22T14:59:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Hover -->
      </class> <!-- com.comprehensive.testCases.Hoveraction_TC -->
    </test> <!-- Test2 -->
    <test name="Test3" duration-ms="18068" started-at="2021-11-22T14:59:36 IST" finished-at="2021-11-22T14:59:54 IST">
      <class name="com.comprehensive.testCases.SearchAction_TC">
        <test-method status="PASS" signature="Search()[pri:0, instance:com.comprehensive.testCases.SearchAction_TC@10feca44]" name="Search" duration-ms="13877" started-at="2021-11-22T14:59:36 IST" finished-at="2021-11-22T14:59:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Search -->
      </class> <!-- com.comprehensive.testCases.SearchAction_TC -->
    </test> <!-- Test3 -->
    <test name="Test4" duration-ms="21491" started-at="2021-11-22T14:59:54 IST" finished-at="2021-11-22T15:00:16 IST">
      <class name="com.comprehensive.testCases.CartCheckout_TC">
        <test-method status="FAIL" signature="cartcheckout()[pri:0, instance:com.comprehensive.testCases.CartCheckout_TC@2053d869]" name="cartcheckout" duration-ms="20854" started-at="2021-11-22T14:59:54 IST" finished-at="2021-11-22T15:00:15 IST">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//a[@data-product-id='6957690618054']"}
  (Session info: chrome=96.0.4664.45)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MT-5CD122JR0C', ip: '192.168.43.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\M1073035\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:51978}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c06321800b36d59d262f3ed5d7739918
*** Element info: {Using=xpath, value=//a[@data-product-id='6957690618054']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@data-product-id='6957690618054']"}
  (Session info: chrome=96.0.4664.45)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MT-5CD122JR0C', ip: '192.168.43.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\M1073035\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:51978}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c06321800b36d59d262f3ed5d7739918
*** Element info: {Using=xpath, value=//a[@data-product-id='6957690618054']}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy28.click(Unknown Source)
at com.comprehensive.testCases.CartCheckout_TC.cartcheckout(CartCheckout_TC.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartcheckout -->
      </class> <!-- com.comprehensive.testCases.CartCheckout_TC -->
    </test> <!-- Test4 -->
    <test name="Test5" duration-ms="24829" started-at="2021-11-22T15:00:16 IST" finished-at="2021-11-22T15:00:41 IST">
      <class name="com.comprehensive.testCases.FeedBack">
        <test-method status="PASS" signature="ContactPage()[pri:0, instance:com.comprehensive.testCases.FeedBack@3d5c822d]" name="ContactPage" duration-ms="20631" started-at="2021-11-22T15:00:16 IST" finished-at="2021-11-22T15:00:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ContactPage -->
      </class> <!-- com.comprehensive.testCases.FeedBack -->
    </test> <!-- Test5 -->
    <test name="Test6" duration-ms="20389" started-at="2021-11-22T15:00:41 IST" finished-at="2021-11-22T15:01:01 IST">
      <class name="com.comprehensive.testCases.GiftCardCheckout">
        <test-method status="PASS" signature="AddGift()[pri:0, instance:com.comprehensive.testCases.GiftCardCheckout@3e84448c]" name="AddGift" duration-ms="20091" started-at="2021-11-22T15:00:41 IST" finished-at="2021-11-22T15:01:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddGift -->
      </class> <!-- com.comprehensive.testCases.GiftCardCheckout -->
    </test> <!-- Test6 -->
    <test name="Test7" duration-ms="28103" started-at="2021-11-22T15:01:01 IST" finished-at="2021-11-22T15:01:29 IST">
      <class name="com.comprehensive.testCases.Wishlistpage_TC">
        <test-method status="PASS" signature="wishlist()[pri:0, instance:com.comprehensive.testCases.Wishlistpage_TC@1b1426f4]" name="wishlist" duration-ms="23887" started-at="2021-11-22T15:01:01 IST" finished-at="2021-11-22T15:01:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wishlist -->
      </class> <!-- com.comprehensive.testCases.Wishlistpage_TC -->
    </test> <!-- Test7 -->
    <test name="Test8" duration-ms="17995" started-at="2021-11-22T15:01:29 IST" finished-at="2021-11-22T15:01:47 IST">
      <class name="com.comprehensive.testCases.HeaderLink_TC">
        <test-method status="PASS" signature="HeaderLinks()[pri:0, instance:com.comprehensive.testCases.HeaderLink_TC@78123e82]" name="HeaderLinks" duration-ms="17871" started-at="2021-11-22T15:01:29 IST" finished-at="2021-11-22T15:01:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HeaderLinks -->
      </class> <!-- com.comprehensive.testCases.HeaderLink_TC -->
    </test> <!-- Test8 -->
    <test name="Test9" duration-ms="20938" started-at="2021-11-22T15:01:47 IST" finished-at="2021-11-22T15:02:08 IST">
      <class name="com.comprehensive.testCases.AllproductTab_TC">
        <test-method status="PASS" signature="AllTab()[pri:0, instance:com.comprehensive.testCases.AllproductTab_TC@2a54a73f]" name="AllTab" duration-ms="16738" started-at="2021-11-22T15:01:47 IST" finished-at="2021-11-22T15:02:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AllTab -->
      </class> <!-- com.comprehensive.testCases.AllproductTab_TC -->
    </test> <!-- Test9 -->
    <test name="Test10" duration-ms="61371" started-at="2021-11-22T15:02:08 IST" finished-at="2021-11-22T15:03:10 IST">
      <class name="com.comprehensive.testCases.RegisterationTest">
        <test-method status="PASS" signature="initalizeDriver()[pri:0, instance:com.comprehensive.testCases.RegisterationTest@383bfa16]" name="initalizeDriver" is-config="true" duration-ms="2116" started-at="2021-11-22T14:58:29 IST" finished-at="2021-11-22T14:58:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initalizeDriver -->
        <test-method status="FAIL" signature="register(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.comprehensive.testCases.RegisterationTest@383bfa16]" name="register" duration-ms="31451" started-at="2021-11-22T15:02:08 IST" data-provider="getData" finished-at="2021-11-22T15:02:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1vjvyj22@hello.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hellohellyggygo123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Gifts Online - Send Unique, Unusual Gifts in India, Buy Gifts– Bigsmall.in] but found [Create Account– Bigsmall.in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Gifts Online - Send Unique, Unusual Gifts in India, Buy Gifts– Bigsmall.in] but found [Create Account– Bigsmall.in]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.comprehensive.testCases.RegisterationTest.register(RegisterationTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="FAIL" signature="register(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.comprehensive.testCases.RegisterationTest@383bfa16]" name="register" duration-ms="21203" started-at="2021-11-22T15:02:44 IST" data-provider="getData" finished-at="2021-11-22T15:03:05 IST">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
            <param index="2">
              <value is-null="true"/>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy28.sendKeys(Unknown Source)
at com.comprehensive.testCases.RegisterationTest.register(RegisterationTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.comprehensive.testCases.RegisterationTest@383bfa16]" name="tearDown" is-config="true" duration-ms="835" started-at="2021-11-22T15:03:10 IST" finished-at="2021-11-22T15:03:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.comprehensive.testCases.RegisterationTest -->
    </test> <!-- Test10 -->
  </suite> <!-- Suite -->
</testng-results>
